name: nootpad
version: 1.1.0
summary: Scratchpad
description: >-
  Simple scratchpad. Kind a 'port' of Boop scratchpad for Linux and Windows
  platforms. Build with Electron and Monaco-editor.
grade: stable
confinement: strict
compression: lzo

apps:
  nootpad:
    extensions: [gnome-3-34]
    plugs:
    - browser-support
    - network
    - network-bind
    - home
    - opengl
    - x11
    - removable-media
    - raw-usb
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    command: nootpad/nootpad --no-sandbox
parts:
  nootpad:
    source: https://github.com/rzrbld/nootpad.git
    source-subdir: src/
    source-type: git
    plugin: nil
    build-environment:
      - ELECTRON_GET_USE_PROXY: 1
    override-build: |
        echo $SNAPCRAFT_PART_INSTALL
        echo "Proxy is:"
        echo $ELECTRON_GET_USE_PROXY
        ls -al
        mv snapcraft/* src/
        cd src
        pwd
        ls -al
        echo "npm install >>>>>>"
        npm install
        npm config set user 0
        npm config set unsafe-perm true
        npm install electron electron-packager
        npx electron-packager . --overwrite --platform=linux --output=release-build --prune=true
        ls -al
        cp -rv ./nootpad-* $SNAPCRAFT_PART_INSTALL/nootpad
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    stage-packages:
      - libnss3
      - libnspr4
    organize:
      nootpad-linux-x64: nootpad
base: core18
plugs:
  browser-sandbox:
    allow-sandbox: true
    interface: browser-support
