name: honk
version: 1.1.0
summary: Scratchpad
description: >-
  Simple scratchpad. Kind a 'port' of Boop scratchpad for Linux and Windows
  platforms. Build with Electron and Monaco-editor.
grade: devel
confinement: classic
apps:
  honk:
    extensions: [gnome-3-34]
    plugs:
    - browser-support
    - network
    - network-bind
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    command: honk/honk --no-sandbox
parts:
  honk:
    source: https://github.com/rzrbld/honk.git
    source-subdir: src/
    source-type: git
    plugin: nil
    override-build: |
        echo $SNAPCRAFT_PART_INSTALL
        ls -al
        mv snapcraft/* src/
        cd src
        pwd
        ls -al
        npm config set user 0
        npm config set unsafe-perm true
        npm install electron electron-packager
        npx electron-packager . --overwrite --platform=linux --output=release-build --prune=true
        ls -al
        cp -rv ./honk-* $SNAPCRAFT_PART_INSTALL/honk
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    stage-packages:
      - libnss3
      - libnspr4
    organize:
      honk-linux-x64: honk
base: core20
plugs:
  browser-sandbox:
    allow-sandbox: true
    interface: browser-support
